[project]
name = "rl-curriculum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "emoji>=2.15.0",
    "open-instruct",
    "pip>=26.0.1",
    "spacy>=3.8.11",
    "syllapy>=0.7.2",
]

[tool.uv]
environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
    "sys_platform == 'linux' and platform_machine == 'aarch64'",
    "sys_platform == 'darwin'",
]

[tool.uv.workspace]
members = ["open-instruct"]


[tool.uv.sources]
open-instruct = { workspace = true }
transformers = { git = "https://github.com/huggingface/transformers.git", branch = "main" }